name: Haldis linter and format
on: [push]
jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Format and lint the codebase
        uses: dagger/dagger-for-github@v2
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          cmds: |
            do lint
